services:
  app:
    image: 'docker.io/jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '81:80'
      - '82:81'
      - '444:443'
    volumes:
      - /opt/docker/volumes/nginx/data:/data
      - /opt/docker/volumes/nginx/letsencrypt:/etc/letsencrypt
