services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:lts
    restart: always
    networks:
      - frontend
      - backend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/docker/volumes/portainer/data:/data
    ports:
      - 9443:9443
#      - 8000:8000  # Remove if you do not intend to use Edge Agents

networks:
  frontend:
    external: true
  backend:
    external: true

